#!/usr/bin/env node

const { spawnSync } = require('node:child_process')
const { mkdtempSync, writeFileSync, rmSync, unlinkSync } = require('node:fs')
const { join } = require('node:path')
const { tmpdir } = require('node:os')

const DEFAULT_DATABASE = process.env.D1_DATABASE_NAME || 'webvault'

const args = process.argv.slice(2)
const mode = args.includes('--remote') ? 'remote' : 'local'
const shouldPrint = args.includes('--print') || args.includes('--preview')
const databaseName = getArgValue('--database') || DEFAULT_DATABASE

const timestampBase = '2025-01-15T09:00:00Z'

const categories = [
  {
    id: 'cat-inspiration',
    name: '发现灵感',
    slug: 'inspiration',
    description: '灵感发现与创意集合平台',
    parentId: null,
    displayOrder: 1,
    icon: 'Sparkles',
    status: 'active',
    createdAt: '2025-01-05T08:00:00Z',
    updatedAt: '2025-02-01T09:30:00Z',
  },
  {
    id: 'cat-inspiration-design',
    name: '设计灵感',
    slug: 'design-inspiration',
    description: '精选 UI/UX 与品牌设计案例',
    parentId: 'cat-inspiration',
    displayOrder: 1,
    icon: 'Palette',
    status: 'active',
    createdAt: '2025-01-06T09:00:00Z',
    updatedAt: '2025-01-28T11:20:00Z',
  },
  {
    id: 'cat-inspiration-photography',
    name: '摄影作品',
    slug: 'photography-showcase',
    description: '摄影作品与视觉故事精选',
    parentId: 'cat-inspiration',
    displayOrder: 2,
    icon: 'Camera',
    status: 'active',
    createdAt: '2025-01-07T11:00:00Z',
    updatedAt: '2025-02-05T10:10:00Z',
  },
  {
    id: 'cat-productivity',
    name: '效率工具',
    slug: 'productivity',
    description: '效率与团队协作工具集合',
    parentId: null,
    displayOrder: 2,
    icon: 'Timer',
    status: 'active',
    createdAt: '2025-01-03T10:00:00Z',
    updatedAt: '2025-01-29T14:40:00Z',
  },
  {
    id: 'cat-productivity-notes',
    name: '笔记与知识库',
    slug: 'knowledge-base',
    description: '个人与团队笔记及知识管理工具',
    parentId: 'cat-productivity',
    displayOrder: 1,
    icon: 'Notebook',
    status: 'active',
    createdAt: '2025-01-04T08:10:00Z',
    updatedAt: '2025-02-08T09:15:00Z',
  },
  {
    id: 'cat-productivity-automation',
    name: '自动化',
    slug: 'workflow-automation',
    description: '自动化脚本与低代码工具',
    parentId: 'cat-productivity',
    displayOrder: 2,
    icon: 'Bot',
    status: 'hidden',
    createdAt: '2025-01-08T07:45:00Z',
    updatedAt: '2025-02-03T12:20:00Z',
  },
  {
    id: 'cat-development',
    name: '开发资源',
    slug: 'development',
    description: '前端、后端与全栈开发资源',
    parentId: null,
    displayOrder: 3,
    icon: 'Code',
    status: 'inactive',
    createdAt: '2025-01-02T12:00:00Z',
    updatedAt: '2025-02-06T16:05:00Z',
  },
]

const tags = [
  {
    id: 'tag-design',
    name: '设计',
    slug: 'design',
    description: '视觉与交互设计资源',
    color: '#F97316',
    isActive: true,
    createdAt: '2025-01-05T09:20:00Z',
    updatedAt: '2025-02-04T13:18:00Z',
  },
  {
    id: 'tag-frontend',
    name: '前端',
    slug: 'frontend',
    description: '前端开发框架与工具',
    color: '#6366F1',
    isActive: true,
    createdAt: '2025-01-05T09:25:00Z',
    updatedAt: '2025-02-02T08:50:00Z',
  },
  {
    id: 'tag-tools',
    name: '工具',
    slug: 'tools',
    description: '实用工具合集',
    color: '#0EA5E9',
    isActive: true,
    createdAt: '2025-01-06T10:05:00Z',
    updatedAt: '2025-02-01T10:22:00Z',
  },
  {
    id: 'tag-efficiency',
    name: '效率',
    slug: 'efficiency',
    description: '效率提升经验与工具',
    color: '#22C55E',
    isActive: true,
    createdAt: '2025-01-06T11:15:00Z',
    updatedAt: '2025-02-07T09:12:00Z',
  },
  {
    id: 'tag-ai',
    name: 'AI',
    slug: 'ai',
    description: '人工智能与生产力应用',
    color: '#A855F7',
    isActive: true,
    createdAt: '2025-01-07T09:40:00Z',
    updatedAt: '2025-02-03T07:40:00Z',
  },
  {
    id: 'tag-photography',
    name: '摄影',
    slug: 'photography',
    description: '摄影作品与教程',
    color: '#FB7185',
    isActive: true,
    createdAt: '2025-01-07T12:30:00Z',
    updatedAt: '2025-02-05T08:25:00Z',
  },
  {
    id: 'tag-learning',
    name: '学习',
    slug: 'learning',
    description: '知识学习与课程平台',
    color: '#14B8A6',
    isActive: true,
    createdAt: '2025-01-08T10:10:00Z',
    updatedAt: '2025-02-06T09:55:00Z',
  },
  {
    id: 'tag-marketing',
    name: '营销',
    slug: 'marketing',
    description: '市场与品牌推广工具',
    color: '#FACC15',
    isActive: false,
    createdAt: '2025-01-08T14:25:00Z',
    updatedAt: '2025-02-04T11:30:00Z',
  },
]

const websites = [
  {
    id: 'site-inspire-gallery',
    title: 'Inspire Gallery',
    slug: 'inspire-gallery',
    description: '每日精选的品牌与界面设计灵感集合。',
    url: 'https://inspire-gallery.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/inspire-gallery.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/inspire-gallery.webp',
    categoryId: 'cat-inspiration-design',
    isFeatured: true,
    rating: 5,
    visitCount: 18450,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-10T08:30:00Z',
    updatedAt: '2025-02-07T09:05:00Z',
    submittedBy: 'admin',
  },
  {
    id: 'site-lens-journal',
    title: 'Lens Journal',
    slug: 'lens-journal',
    description: '记录世界角度的摄影作品社群。',
    url: 'https://lens-journal.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/lens-journal.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/lens-journal.webp',
    categoryId: 'cat-inspiration-photography',
    rating: 4,
    visitCount: 9600,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-11T09:00:00Z',
    updatedAt: '2025-02-02T11:42:00Z',
  },
  {
    id: 'site-creative-brew',
    title: 'Creative Brew',
    slug: 'creative-brew',
    description: '设计师访谈与创意流程分享。',
    url: 'https://creative-brew.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/creative-brew.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/creative-brew.webp',
    categoryId: 'cat-inspiration-design',
    isAd: true,
    adType: 'sponsored',
    rating: 4,
    visitCount: 5400,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-12T07:20:00Z',
    updatedAt: '2025-02-06T10:10:00Z',
    notes: '赞助栏目位',
  },
  {
    id: 'site-notion-flow',
    title: 'Notion Flow Templates',
    slug: 'notion-flow',
    description: 'Notion 系统化模板集，助力知识管理。',
    url: 'https://notion-flow.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/notion-flow.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/notion-flow.webp',
    categoryId: 'cat-productivity-notes',
    isFeatured: true,
    rating: 5,
    visitCount: 22800,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-09T09:45:00Z',
    updatedAt: '2025-02-07T12:00:00Z',
  },
  {
    id: 'site-focus-track',
    title: 'FocusTrack',
    slug: 'focus-track',
    description: '跨平台的时间追踪与番茄钟工具。',
    url: 'https://focus-track.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/focus-track.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/focus-track.webp',
    categoryId: 'cat-productivity',
    rating: 4,
    visitCount: 12500,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-13T10:30:00Z',
    updatedAt: '2025-02-05T09:33:00Z',
  },
  {
    id: 'site-automation-lab',
    title: 'Automation Lab',
    slug: 'automation-lab',
    description: '自动化脚本示例库，轻松整合常用服务。',
    url: 'https://automation-lab.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/automation-lab.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/automation-lab.webp',
    categoryId: 'cat-productivity-automation',
    rating: 3,
    visitCount: 4200,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-14T11:50:00Z',
    updatedAt: '2025-02-03T10:48:00Z',
  },
  {
    id: 'site-task-bridge',
    title: 'TaskBridge',
    slug: 'task-bridge',
    description: '团队任务与 OKR 协同工作台。',
    url: 'https://task-bridge.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/task-bridge.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/task-bridge.webp',
    categoryId: 'cat-productivity',
    rating: 4,
    visitCount: 8600,
    status: 'pending',
    reviewStatus: 'pending',
    createdAt: '2025-01-16T09:20:00Z',
    updatedAt: '2025-02-01T08:10:00Z',
    submittedBy: 'team@taskbridge.io',
  },
  {
    id: 'site-dev-radar',
    title: 'Dev Radar',
    slug: 'dev-radar',
    description: '精选前端生态与工具趋势周报。',
    url: 'https://dev-radar.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/dev-radar.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/dev-radar.webp',
    categoryId: 'cat-development',
    isFeatured: true,
    rating: 5,
    visitCount: 19200,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-18T08:40:00Z',
    updatedAt: '2025-02-08T14:45:00Z',
  },
  {
    id: 'site-frontier-docs',
    title: 'Frontier Docs',
    slug: 'frontier-docs',
    description: '深度前端架构与性能优化案例集。',
    url: 'https://frontier-docs.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/frontier-docs.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/frontier-docs.webp',
    categoryId: 'cat-development',
    rating: 5,
    visitCount: 15600,
    status: 'inactive',
    reviewStatus: 'pending',
    createdAt: '2025-01-19T10:15:00Z',
    updatedAt: '2025-02-04T09:25:00Z',
  },
  {
    id: 'site-ai-sprint',
    title: 'AI Sprint',
    slug: 'ai-sprint',
    description: 'AI 辅助的创意头脑风暴与写作助手。',
    url: 'https://ai-sprint.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/ai-sprint.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/ai-sprint.webp',
    categoryId: 'cat-productivity-automation',
    isFeatured: true,
    rating: 5,
    visitCount: 21100,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-20T12:00:00Z',
    updatedAt: '2025-02-06T16:20:00Z',
    submittedBy: 'studio@aisprint.dev',
  },
  {
    id: 'site-photo-scout',
    title: 'Photo Scout',
    slug: 'photo-scout',
    description: '城市与自然取景地数据库。',
    url: 'https://photo-scout.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/photo-scout.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/photo-scout.webp',
    categoryId: 'cat-inspiration-photography',
    isAd: true,
    adType: 'banner',
    rating: 4,
    visitCount: 7300,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-17T09:05:00Z',
    updatedAt: '2025-02-05T12:32:00Z',
  },
  {
    id: 'site-growth-hub',
    title: 'Growth Hub',
    slug: 'growth-hub',
    description: 'SaaS 营销增长案例和工具导航。',
    url: 'https://growth-hub.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/growth-hub.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/growth-hub.webp',
    categoryId: 'cat-development',
    rating: 3,
    visitCount: 5200,
    status: 'active',
    reviewStatus: 'approved',
    isPublic: false,
    createdAt: '2025-01-21T11:25:00Z',
    updatedAt: '2025-02-02T10:55:00Z',
    notes: '内部审核中',
  },
  {
    id: 'site-design-digest',
    title: 'Design Digest',
    slug: 'design-digest',
    description: '精选 UI/UX 资源与设计系统案例合集。',
    url: 'https://design-digest.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/design-digest.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/design-digest.webp',
    categoryId: 'cat-inspiration-design',
    isFeatured: true,
    rating: 4,
    visitCount: 8400,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-22T09:00:00Z',
    updatedAt: '2025-02-10T08:20:00Z',
  },
  {
    id: 'site-pixel-playground',
    title: 'Pixel Playground',
    slug: 'pixel-playground',
    description: '在线组件和插画生成工具合集。',
    url: 'https://pixel-playground.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/pixel-playground.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/pixel-playground.webp',
    categoryId: 'cat-inspiration-design',
    rating: 5,
    visitCount: 9100,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-23T10:15:00Z',
    updatedAt: '2025-02-07T12:45:00Z',
  },
  {
    id: 'site-workflow-hub',
    title: 'Workflow Hub',
    slug: 'workflow-hub',
    description: '团队自动化流程模板与最佳实践。',
    url: 'https://workflow-hub.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/workflow-hub.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/workflow-hub.webp',
    categoryId: 'cat-productivity-automation',
    rating: 4,
    visitCount: 6700,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-23T14:20:00Z',
    updatedAt: '2025-02-04T09:18:00Z',
  },
  {
    id: 'site-focus-lab',
    title: 'Focus Lab',
    slug: 'focus-lab',
    description: '正念与专注力提升的课程与工具。',
    url: 'https://focus-lab.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/focus-lab.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/focus-lab.webp',
    categoryId: 'cat-productivity',
    rating: 3,
    visitCount: 4500,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-24T08:35:00Z',
    updatedAt: '2025-02-05T10:40:00Z',
  },
  {
    id: 'site-async-daily',
    title: 'Async Daily',
    slug: 'async-daily',
    description: '远程团队协作与异步沟通指南。',
    url: 'https://async-daily.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/async-daily.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/async-daily.webp',
    categoryId: 'cat-productivity',
    rating: 4,
    visitCount: 5200,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-24T11:10:00Z',
    updatedAt: '2025-02-03T13:32:00Z',
  },
  {
    id: 'site-sprint-stories',
    title: 'Sprint Stories',
    slug: 'sprint-stories',
    description: '记录敏捷团队迭代与复盘的博客。',
    url: 'https://sprint-stories.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/sprint-stories.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/sprint-stories.webp',
    categoryId: 'cat-productivity',
    rating: 3,
    visitCount: 3800,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-25T09:05:00Z',
    updatedAt: '2025-02-08T14:12:00Z',
  },
  {
    id: 'site-ai-canvas',
    title: 'AI Canvas',
    slug: 'ai-canvas',
    description: 'AI 生成艺术作品的灵感图库。',
    url: 'https://ai-canvas.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/ai-canvas.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/ai-canvas.webp',
    categoryId: 'cat-inspiration',
    isFeatured: true,
    rating: 5,
    visitCount: 15700,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-25T13:30:00Z',
    updatedAt: '2025-02-09T11:40:00Z',
  },
  {
    id: 'site-lens-lab',
    title: 'Lens Lab',
    slug: 'lens-lab',
    description: '摄影技巧、设备评测与后期教程。',
    url: 'https://lens-lab.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/lens-lab.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/lens-lab.webp',
    categoryId: 'cat-inspiration-photography',
    rating: 4,
    visitCount: 10400,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-26T10:05:00Z',
    updatedAt: '2025-02-06T09:48:00Z',
  },
  {
    id: 'site-contrast-club',
    title: 'Contrast Club',
    slug: 'contrast-club',
    description: '创意对比案例与灵感讨论社区。',
    url: 'https://contrast-club.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/contrast-club.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/contrast-club.webp',
    categoryId: 'cat-inspiration',
    isAd: true,
    adType: 'sponsored',
    rating: 4,
    visitCount: 6900,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-26T15:45:00Z',
    updatedAt: '2025-02-04T08:55:00Z',
  },
  {
    id: 'site-snapshot-map',
    title: 'Snapshot Map',
    slug: 'snapshot-map',
    description: '全球摄影地点地图与旅行指南。',
    url: 'https://snapshot-map.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/snapshot-map.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/snapshot-map.webp',
    categoryId: 'cat-inspiration-photography',
    rating: 5,
    visitCount: 13800,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-27T09:55:00Z',
    updatedAt: '2025-02-05T13:05:00Z',
  },
  {
    id: 'site-blueprint-dev',
    title: 'Blueprint Dev',
    slug: 'blueprint-dev',
    description: '现代前端架构与工程化指南。',
    url: 'https://blueprint-dev.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/blueprint-dev.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/blueprint-dev.webp',
    categoryId: 'cat-development',
    rating: 5,
    visitCount: 11200,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-27T13:20:00Z',
    updatedAt: '2025-02-08T10:26:00Z',
  },
  {
    id: 'site-stack-garden',
    title: 'Stack Garden',
    slug: 'stack-garden',
    description: '精选开发工具、模板与最佳实践。',
    url: 'https://stack-garden.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/stack-garden.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/stack-garden.webp',
    categoryId: 'cat-development',
    rating: 4,
    visitCount: 7600,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-28T10:12:00Z',
    updatedAt: '2025-02-03T15:45:00Z',
  },
  {
    id: 'site-shipmate',
    title: 'Shipmate',
    slug: 'shipmate',
    description: '产品发布节奏与上线计划管理工具。',
    url: 'https://shipmate.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/shipmate.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/shipmate.webp',
    categoryId: 'cat-productivity',
    isFeatured: true,
    rating: 4,
    visitCount: 9800,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-28T14:05:00Z',
    updatedAt: '2025-02-09T11:30:00Z',
  },
  {
    id: 'site-idea-forge',
    title: 'Idea Forge',
    slug: 'idea-forge',
    description: '创意工作坊与头脑风暴资源中心。',
    url: 'https://idea-forge.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/idea-forge.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/idea-forge.webp',
    categoryId: 'cat-inspiration',
    rating: 4,
    visitCount: 6200,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-29T09:40:00Z',
    updatedAt: '2025-02-02T16:00:00Z',
  },
  {
    id: 'site-cursor-lab',
    title: 'Cursor Lab',
    slug: 'cursor-lab',
    description: 'AI 辅助代码实验室与提示工程分享。',
    url: 'https://cursor-lab.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/cursor-lab.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/cursor-lab.webp',
    categoryId: 'cat-productivity-automation',
    isAd: true,
    adType: 'banner',
    rating: 5,
    visitCount: 14200,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-29T13:15:00Z',
    updatedAt: '2025-02-06T12:25:00Z',
  },
  {
    id: 'site-chrono-hub',
    title: 'Chrono Hub',
    slug: 'chrono-hub',
    description: '可视化时间管理与习惯追踪平台。',
    url: 'https://chrono-hub.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/chrono-hub.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/chrono-hub.webp',
    categoryId: 'cat-productivity',
    rating: 4,
    visitCount: 8700,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-30T08:55:00Z',
    updatedAt: '2025-02-08T09:45:00Z',
  },
  {
    id: 'site-clarity-notes',
    title: 'Clarity Notes',
    slug: 'clarity-notes',
    description: '结构化知识库与第二大脑构建指南。',
    url: 'https://clarity-notes.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/clarity-notes.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/clarity-notes.webp',
    categoryId: 'cat-productivity-notes',
    rating: 5,
    visitCount: 13400,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-30T12:10:00Z',
    updatedAt: '2025-02-05T08:30:00Z',
  },
  {
    id: 'site-arcade-ui',
    title: 'Arcade UI',
    slug: 'arcade-ui',
    description: '复古风格 UI 元素与动效库。',
    url: 'https://arcade-ui.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/arcade-ui.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/arcade-ui.webp',
    categoryId: 'cat-inspiration-design',
    rating: 4,
    visitCount: 7400,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-31T09:25:00Z',
    updatedAt: '2025-02-03T10:55:00Z',
  },
  {
    id: 'site-pathfinder',
    title: 'Pathfinder',
    slug: 'pathfinder',
    description: '产品路线图与案例拆解数据库。',
    url: 'https://pathfinder.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/pathfinder.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/pathfinder.webp',
    categoryId: 'cat-inspiration',
    rating: 4,
    visitCount: 6800,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-01-31T14:40:00Z',
    updatedAt: '2025-02-06T11:05:00Z',
  },
  {
    id: 'site-aurora-press',
    title: 'Aurora Press',
    slug: 'aurora-press',
    description: '创意写作与品牌故事研习社。',
    url: 'https://aurora-press.example.com',
    faviconUrl: 'https://assets.webvault.dev/icons/aurora-press.png',
    screenshotUrl: 'https://assets.webvault.dev/screenshots/aurora-press.webp',
    categoryId: 'cat-inspiration',
    rating: 4,
    visitCount: 5600,
    status: 'active',
    reviewStatus: 'approved',
    createdAt: '2025-02-01T09:05:00Z',
    updatedAt: '2025-02-07T09:58:00Z',
  },
]

const websiteTagsMapping = [
  { websiteId: 'site-inspire-gallery', tagId: 'tag-design', assignedAt: timestampBase },
  { websiteId: 'site-inspire-gallery', tagId: 'tag-learning', assignedAt: timestampBase },
  { websiteId: 'site-lens-journal', tagId: 'tag-photography', assignedAt: timestampBase },
  { websiteId: 'site-lens-journal', tagId: 'tag-design', assignedAt: timestampBase },
  { websiteId: 'site-creative-brew', tagId: 'tag-design', assignedAt: timestampBase },
  { websiteId: 'site-creative-brew', tagId: 'tag-marketing', assignedAt: timestampBase },
  { websiteId: 'site-notion-flow', tagId: 'tag-efficiency', assignedAt: timestampBase },
  { websiteId: 'site-notion-flow', tagId: 'tag-learning', assignedAt: timestampBase },
  { websiteId: 'site-focus-track', tagId: 'tag-efficiency', assignedAt: timestampBase },
  { websiteId: 'site-focus-track', tagId: 'tag-tools', assignedAt: timestampBase },
  { websiteId: 'site-automation-lab', tagId: 'tag-tools', assignedAt: timestampBase },
  { websiteId: 'site-automation-lab', tagId: 'tag-efficiency', assignedAt: timestampBase },
  { websiteId: 'site-task-bridge', tagId: 'tag-efficiency', assignedAt: timestampBase },
  { websiteId: 'site-task-bridge', tagId: 'tag-tools', assignedAt: timestampBase },
  { websiteId: 'site-dev-radar', tagId: 'tag-frontend', assignedAt: timestampBase },
  { websiteId: 'site-dev-radar', tagId: 'tag-learning', assignedAt: timestampBase },
  { websiteId: 'site-frontier-docs', tagId: 'tag-frontend', assignedAt: timestampBase },
  { websiteId: 'site-frontier-docs', tagId: 'tag-learning', assignedAt: timestampBase },
  { websiteId: 'site-ai-sprint', tagId: 'tag-ai', assignedAt: timestampBase },
  { websiteId: 'site-ai-sprint', tagId: 'tag-tools', assignedAt: timestampBase },
  { websiteId: 'site-photo-scout', tagId: 'tag-photography', assignedAt: timestampBase },
  { websiteId: 'site-photo-scout', tagId: 'tag-design', assignedAt: timestampBase },
  { websiteId: 'site-growth-hub', tagId: 'tag-marketing', assignedAt: timestampBase },
  { websiteId: 'site-growth-hub', tagId: 'tag-tools', assignedAt: timestampBase },
  { websiteId: 'site-design-digest', tagId: 'tag-design', assignedAt: timestampBase },
  { websiteId: 'site-design-digest', tagId: 'tag-learning', assignedAt: timestampBase },
  { websiteId: 'site-pixel-playground', tagId: 'tag-design', assignedAt: timestampBase },
  { websiteId: 'site-pixel-playground', tagId: 'tag-tools', assignedAt: timestampBase },
  { websiteId: 'site-workflow-hub', tagId: 'tag-efficiency', assignedAt: timestampBase },
  { websiteId: 'site-workflow-hub', tagId: 'tag-tools', assignedAt: timestampBase },
  { websiteId: 'site-focus-lab', tagId: 'tag-efficiency', assignedAt: timestampBase },
  { websiteId: 'site-async-daily', tagId: 'tag-efficiency', assignedAt: timestampBase },
  { websiteId: 'site-async-daily', tagId: 'tag-tools', assignedAt: timestampBase },
  { websiteId: 'site-sprint-stories', tagId: 'tag-learning', assignedAt: timestampBase },
  { websiteId: 'site-ai-canvas', tagId: 'tag-ai', assignedAt: timestampBase },
  { websiteId: 'site-ai-canvas', tagId: 'tag-design', assignedAt: timestampBase },
  { websiteId: 'site-lens-lab', tagId: 'tag-photography', assignedAt: timestampBase },
  { websiteId: 'site-lens-lab', tagId: 'tag-learning', assignedAt: timestampBase },
  { websiteId: 'site-contrast-club', tagId: 'tag-design', assignedAt: timestampBase },
  { websiteId: 'site-snapshot-map', tagId: 'tag-photography', assignedAt: timestampBase },
  { websiteId: 'site-blueprint-dev', tagId: 'tag-frontend', assignedAt: timestampBase },
  { websiteId: 'site-blueprint-dev', tagId: 'tag-learning', assignedAt: timestampBase },
  { websiteId: 'site-stack-garden', tagId: 'tag-frontend', assignedAt: timestampBase },
  { websiteId: 'site-stack-garden', tagId: 'tag-tools', assignedAt: timestampBase },
  { websiteId: 'site-shipmate', tagId: 'tag-efficiency', assignedAt: timestampBase },
  { websiteId: 'site-shipmate', tagId: 'tag-tools', assignedAt: timestampBase },
  { websiteId: 'site-idea-forge', tagId: 'tag-design', assignedAt: timestampBase },
  { websiteId: 'site-idea-forge', tagId: 'tag-learning', assignedAt: timestampBase },
  { websiteId: 'site-cursor-lab', tagId: 'tag-ai', assignedAt: timestampBase },
  { websiteId: 'site-cursor-lab', tagId: 'tag-tools', assignedAt: timestampBase },
  { websiteId: 'site-chrono-hub', tagId: 'tag-efficiency', assignedAt: timestampBase },
  { websiteId: 'site-clarity-notes', tagId: 'tag-learning', assignedAt: timestampBase },
  { websiteId: 'site-clarity-notes', tagId: 'tag-efficiency', assignedAt: timestampBase },
  { websiteId: 'site-arcade-ui', tagId: 'tag-design', assignedAt: timestampBase },
  { websiteId: 'site-pathfinder', tagId: 'tag-learning', assignedAt: timestampBase },
  { websiteId: 'site-aurora-press', tagId: 'tag-design', assignedAt: timestampBase },
  { websiteId: 'site-aurora-press', tagId: 'tag-learning', assignedAt: timestampBase },
]

const sqlStatements = buildSeedSql()

if (shouldPrint) {
  console.log(sqlStatements)
  process.exit(0)
}

const tmpDir = mkdtempSync(join(tmpdir(), 'webvault-seed-'))
const sqlFile = join(tmpDir, 'seed.sql')

writeFileSync(sqlFile, sqlStatements, 'utf8')

const wranglerArgs = ['d1', 'execute', databaseName]
if (mode === 'local') {
  wranglerArgs.push('--local')
}
wranglerArgs.push('--file', sqlFile)

const result = spawnSync('wrangler', wranglerArgs, { stdio: 'inherit' })

cleanupTemp(sqlFile, tmpDir)

if (result.error) {
  console.error('执行 wrangler 时出错:', result.error.message)
  process.exit(1)
}

if (typeof result.status === 'number' && result.status !== 0) {
  process.exit(result.status)
}

console.log(`✅ 数据已插入 ${mode === 'local' ? '本地' : '远程'} D1 数据库 (${databaseName})`)

function buildSeedSql() {
  const lines = []
  lines.push('PRAGMA foreign_keys = ON;')
  lines.push('BEGIN TRANSACTION;')
  lines.push('DELETE FROM website_tags;')
  lines.push('DELETE FROM websites;')
  lines.push('DELETE FROM categories;')
  lines.push('DELETE FROM tags;')

  for (const category of categories) {
    lines.push(
      `INSERT INTO categories (id, name, slug, description, parent_id, display_order, icon, is_active, status, created_at, updated_at) VALUES (${sqlValue(category.id)}, ${sqlValue(category.name)}, ${sqlValue(category.slug)}, ${sqlValue(category.description)}, ${sqlValue(category.parentId)}, ${sqlValue(category.displayOrder)}, ${sqlValue(category.icon)}, ${sqlValue(category.status === 'active')}, ${sqlValue(category.status)}, ${sqlValue(category.createdAt)}, ${sqlValue(category.updatedAt)});`
    )
  }

  for (const tag of tags) {
    lines.push(
      `INSERT INTO tags (id, name, slug, description, color, is_active, created_at, updated_at) VALUES (${sqlValue(tag.id)}, ${sqlValue(tag.name)}, ${sqlValue(tag.slug)}, ${sqlValue(tag.description)}, ${sqlValue(tag.color)}, ${sqlValue(tag.isActive)}, ${sqlValue(tag.createdAt)}, ${sqlValue(tag.updatedAt)});`
    )
  }

  for (const site of websites) {
    lines.push(
      `INSERT INTO websites (id, title, description, url, slug, favicon_url, screenshot_url, category_id, is_ad, ad_type, rating, visit_count, is_featured, is_public, status, review_status, notes, submitted_by, created_at, updated_at) VALUES (${sqlValue(site.id)}, ${sqlValue(site.title)}, ${sqlValue(site.description)}, ${sqlValue(site.url)}, ${sqlValue(site.slug)}, ${sqlValue(site.faviconUrl)}, ${sqlValue(site.screenshotUrl)}, ${sqlValue(site.categoryId)}, ${sqlValue(site.isAd || false)}, ${sqlValue(site.adType)}, ${sqlValue(site.rating)}, ${sqlValue(site.visitCount || 0)}, ${sqlValue(site.isFeatured || false)}, ${sqlValue(site.isPublic !== false)}, ${sqlValue(site.status || 'active')}, ${sqlValue(site.reviewStatus || 'pending')}, ${sqlValue(site.notes)}, ${sqlValue(site.submittedBy)}, ${sqlValue(site.createdAt)}, ${sqlValue(site.updatedAt)});`
    )
  }

  for (const mapping of websiteTagsMapping) {
    lines.push(
      `INSERT INTO website_tags (website_id, tag_id, assigned_at) VALUES (${sqlValue(mapping.websiteId)}, ${sqlValue(mapping.tagId)}, ${sqlValue(mapping.assignedAt)});`
    )
  }

  lines.push('COMMIT;')
  return lines.join('\n') + '\n'
}

function sqlValue(value) {
  if (value === null || value === undefined) {
    return 'NULL'
  }
  if (typeof value === 'boolean') {
    return value ? '1' : '0'
  }
  if (typeof value === 'number') {
    return Number.isFinite(value) ? String(value) : 'NULL'
  }
  return `'${String(value).replace(/'/g, "''")}'`
}

function getArgValue(flag) {
  const index = args.findIndex((arg) => arg === flag)
  if (index !== -1 && index + 1 < args.length) {
    return args[index + 1]
  }
  return null
}

function cleanupTemp(filePath, dirPath) {
  try {
    unlinkSync(filePath)
    rmSync(dirPath, { recursive: true, force: true })
  } catch (error) {
    console.warn('清理临时文件失败:', error)
  }
}
