name = "webvault"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "webvault"
database_id = "0300606c-7656-4f1b-8279-be081621b727"
