[project]
name = "WebVault"
root_path = ".."

default_agents = ["claude", "codex"]

[sources]
agents_md = "AGENTS.md"
project_md = "PROJECT.md"

[outputs]
claude = "CLAUDE.md"
agents = "AGENTS.md"

# 明确启用需要的 agents
[agents.claude]
enabled = true
output_path = "CLAUDE.md"

[agents.codex]
enabled = true
output_path = "AGENTS.md"

[includes]
specs = ["specs/*.md"]
stacks = ["stacks/*.md"]
structures = ["structures/*.md"]
docs = ["docs/*.md"]

[gitignore]
enabled = false